#!/usr/bin/env bash 
# to configure web-01 to have HTTP response header

# updating the packages 
sudo apt-get update 
sudo apt-get install -y nginx 

#creating an index page 
echo "Hello World!" | sudo tee /var/www/html/index.html

# performing a redirection
new_string= "server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/oladakinjoye permanent;"

sudo sed -i "server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom HTTP header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# to test for syntax errors 
sudo nginx -t 
# restart the nginx service 
sudo service nginx restart
