#!/usr/bin/env bash
# to configure web-01 to have HTTP response header

# updating packages before installations
sudo apt-get update
sudo apt-get install -y nginx

# creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# performing redirection" 
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/oladakinjoye permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# creating an HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# checking configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
