#!/usr/bin/env bash
# to create a script to install and configure HAProxy on lb-01 server
# to configure HAProxy to send traffic to web-01 and web-02 servers
# distribute requests using a roundrobin algorithm
# make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  oladakinjoye_frontend
        bind *:80
        mode http
        default_backend oladakinjoye_backend
backend oladakinjoye_backend
        balance roundrobin
        server 496097-web-01 52.3.70.215:80 check
        server 496097-web-02 54.144.156.78:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
