#!/usr/bin/env bash
# To configure an Ubuntu server as follows:
#   - localhost resolve to 127.0.0.2
#   - facebook.com resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
